packages:
  - 'apps/frontend/healthproof-frontend'
  - 'apps/backend'

pnpm:
  packageExtensions:
    "@privy-io/react-auth":
      dependencies:
        '@walletconnect/ethereum-provider': ^2.21.0
        '@solana-program/token-2022': ^0.12.0
        '@solana-program/token': ^0.14.0
        '@solana-program/system': ^0.12.2
        '@solana/kit': ^6.10.0
        '@solana/sysvars': ^5.5.1
    x402:
      dependencies:
        '@solana-program/token-2022': ^0.12.0
        '@solana-program/token': ^0.14.0
        '@solana-program/system': ^0.12.2
        '@solana/kit': ^6.10.0
        '@solana/sysvars': ^5.5.1
